tasks:
  - init: NG_CLI_ANALYTICS=ci npm install
    command: npm start
ports:
  - port: 4455
    onOpen: open-preview
  - port: 8099
    onOpen: ignore
  - port: 5958
    onOpen: ignore
#vscode:
#  extensions:
#    - Angular.ng-template
#    - esbenp.prettier-vscode
